language: node_js
node_js:
  - stable
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - npm install eslint
  - npm install broccoli
script:
  - ./node_modules/eslint/bin/eslint.js js/
  - ./node_modules/eslint/bin/broccoli build dist
